INCLUDE(FindPackageHandleStandardArgs)
SET(TAPKEE_FOUND FALSE)

MESSAGE(STATUS "Looking for tapkee: ${TAPKEE_DIR}")

IF(NOT EIGEN3_FOUND)
  MESSAGE(WARNING "Tapkee requires Eigen3, which has not been found.")
ENDIF(NOT EIGEN3_FOUND)

IF(TAPKEE_INCLUDE_DIR)
  SET(TAPKEE_FOUND TRUE)
ELSE(TAPKEE_INCLUDE_DIR)
  FIND_PATH(TAPKEE_INCLUDE_DIR 
    NAMES tapkee/tapkee.hpp
    HINTS ENV TAPKEE_DIR 
    PATHS ${TAPKEE_DIR}/include
    PATH_SUFFIXES tapkee)

  IF(TAPKEE_INCLUDE_DIR)
    SET(TAPKEE_FOUND TRUE)
  ENDIF(TAPKEE_INCLUDE_DIR)

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(tapkee_library DEFAULT_MSG TAPKEE_INCLUDE_DIR TAPKEE_FOUND)
  MARK_AS_ADVANCED(TAPKEE_INCLUDE_DIR)
ENDIF(TAPKEE_INCLUDE_DIR)

IF(TAPKEE_FOUND AND NOT TARGET tapkee_library)
  ADD_LIBRARY(tapkee_library INTERFACE IMPORTED)
  SET_TARGET_PROPERTIES(tapkee_library PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${TAPKEE_INCLUDE_DIR}")

  IF(EIGEN3_FOUND)
    SET_TARGET_PROPERTIES(tapkee_library PROPERTIES INTERFACE_COMPILE_DEFINITIONS "-DTAPKEE_EIGEN_INCLUDE_FILE=\"${EIGEN3_INCLUDE_DIR}Eigen/Eigen\"")
  ENDIF(EIGEN3_FOUND)
ENDIF(TAPKEE_FOUND AND NOT TARGET tapkee_library)